---
title: "MRP with CmdStanR"
author: "Jonah Gabry"
date: "8/4/2020"
output: html_document
---

```{r setup, message=FALSE}
library(cmdstanr)
library(bayesplot)
library(posterior)

bayesplot::color_scheme_set("brightblue")
cmdstanr::register_knitr_engine(override = FALSE)
knitr::opts_chunk$set(cache = TRUE)
```

## Simulate data


```{r simulate-data}
set.seed(101)
N <- 2000
N_age <- 4
N_income <- 5
N_state <- 50

sigma_age <- abs(rnorm(1, 0, 1))
sigma_income <- abs(rnorm(1, 0, 1))
sigma_state <- abs(rnorm(1, 0, 1))

alpha_global <- rnorm(1, 0, 5)
beta_state_income <- rnorm(1, 0, 2) # coef on avg state income

alpha_age <- rnorm(N_age, 0, sigma_age)
alpha_income <- rnorm(N_income, 0, sigma_income)
alpha_state <- rnorm(N_state, 0, sigma_state)

data <- data.frame(
  age = sample(N_age, size = N, replace = TRUE),
  income = sample(N_income, size = N, replace = TRUE),
  state = sample(N_state, size = N, replace = TRUE)
)

# as if it were standardized
data$state_avg_income <- rnorm(N_state, 0, 1)[data$state]

data$pr <- with(data, plogis(
  alpha_global + beta_state_income * state_avg_income + 
    alpha_age[age] + alpha_income[income] + alpha_state[state]
))
data$y <- rbinom(N, size = 1, prob = data$pr)

# population frequencies for postratification
pop_freq_array <- xtabs(formula = ~ age + income + state, data = data)
pop_freq_df <- as.data.frame(pop_freq_array)
class(pop_freq_array) <- "array"

stan_data <- list(
  N = N,
  pop_freq = pop_freq_array,
  y = data$y,
  age = data$age,
  income = data$income,
  state = data$state,
  state_avg_income = unique(data$state_avg_income)
)
```


## Fit model

```{cmdstan stan-program, output.var = "mod"}
data {
  int<lower = 0> N;
  int<lower = 1, upper = 4> age[N];
  int<lower = 1, upper = 5> income[N];
  int<lower = 1, upper = 50> state[N];
  vector[50] state_avg_income; // standardized
  int<lower = 0> y[N];
  int<lower = 0> pop_freq[4, 5, 50];
}
parameters {
  real alpha_global;
  real beta_state_income;
  real<lower = 0> sigma_age;
  vector<multiplier = sigma_age>[4] alpha_age;
  real<lower = 0> sigma_income;
  vector<multiplier = sigma_income>[5] alpha_income;
  real<lower = 0> sigma_state;
  vector<multiplier = sigma_state>[50] alpha_state;
}
model {
  y ~ bernoulli_logit(
    alpha_global +
    alpha_age[age] + alpha_income[income] + alpha_state[state] +
    beta_state_income * state_avg_income[state]
  );
  alpha_global ~ normal(0, 2);
  alpha_age ~ normal(0, sigma_age);
  alpha_income ~ normal(0, sigma_income);
  alpha_state ~ normal(0, sigma_state);
  beta_state_income ~ normal(0, 2);
  sigma_age ~ normal(0, 1);
  sigma_income ~ normal(0, 1);
  sigma_state ~ normal(0, 1);
}
generated quantities {
  real<lower = 0, upper = 1> overall_prob;
  real<lower=0,upper=1> cell_probs[4, 5, 50];
  real cell_expects[4, 5, 50];
  {
  real expect_pos = 0;
  int total = 0;
  for (b in 1:4)
    for (c in 1:5)
      for (d in 1:50) {
        cell_probs[b, c, d] = inv_logit(
          alpha_global +
          alpha_age[b] + alpha_income[c] + alpha_state[d] +
          beta_state_income * state_avg_income[d]
        );
        cell_expects[b, c, d] = pop_freq[b, c, d] * cell_probs[b, c, d];

        total += pop_freq[b, c, d];
        expect_pos += cell_expects[b, c, d];
      }
   overall_prob = expect_pos / total;
  }
}
```

```{r compile}
# mod <- cmdstan_model("mrp.stan")
mod$print()
```

```{r fit}
fit <- mod$sample(data = stan_data, parallel_chains = 4, show_messages = FALSE)
```

## Summarizing estimates
```{r summary}
fit$summary("alpha_income")
fit$summary("overall_prob")
```

## Plotting estimates
```{r plot}
mcmc_hist(fit$draws("overall_prob"))
mcmc_intervals(fit$draws("alpha_age"))
mcmc_intervals(fit$draws("alpha_income"))
```

## Computing population estimate

```{r population}
cell_probs <- fit$draws("cell_probs")
cell_probs <- as_draws_matrix(cell_probs)
dim(cell_probs)

# compute population probability from cell_probs and poststrat table
# and compare to what we computed in generated quantities

pop_prob <- mean(cell_probs %*% pop_freq_df$Freq / sum(pop_freq_df$Freq))
mcmc_hist(fit$draws("overall_prob")) + vline_at(pop_prob, color = "black", size = 2)
```

## Computing state-specific estimates

```{r states}
# Plot state-specific estimates
state_probs <- matrix(NA, nrow = nrow(cell_probs), ncol = 50)
for (j in 1:50) {
  select_state_j <- pop_freq_df$state == j
  state_probs[, j] <- 
    (cell_probs[, select_state_j] %*% pop_freq_df$Freq[select_state_j]) /
    sum(pop_freq_df$Freq[pop_freq_df$state == j])  
}
colnames(state_probs) <- state.abb
mcmc_intervals(state_probs) + vline_at(pop_prob, linetype = 2)
```
